Quizzicle/Quizzicle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('quizzes.urls')),
]

Quizzicle/quizzes/urls.py
from django.urls import path, include

from quizzes import views

create_patterns = [
    path("", views.view_created_quizzes, name="view_quizzes"),
    path("create_quiz/", views.create_quiz, name="create_quiz"),
    path("modify_quiz/<int:id>/", views.modify_quiz, name="modify_quiz"),
    path("delete_quiz/<int:id>/", views.delete_quiz, name="delete_quiz"),
    path("delete_question/<int:id>", views.delete_question, name="delete_question"),
    path("create_question/<int:id>", views.create_question, name="create_question"),
    path("modify_question/<int:id>/", views.modify_question, name="modify_question"),
    path("create_choice/<int:id>/", views.create_choice, name="create_choice"),

    path("update_choice/<int:id>", views.modify_choice, name="modify_choice")
]

urlpatterns = [
    path("create", include(create_patterns)),
    path("", views.get_home, name="home"),
    path("search/", views.get_search_results, name="search"),
    path("quizzes/prepare_quiz/<int:id>", views.prepare_quiz, name="prepare_quiz"),
    path("quizzes/take_quiz/<int:id>", views.take_quiz, name="take_quiz"),
    path("quizzes/results/<int:id>", views.get_results, name="results")
]

Quizzicle/quizzes/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Quiz(models.Model):
    class Subject(models.TextChoices):
        MATH = "MA"
        SCIENCE = "SC"
        HISTORY = "HI"
        ENGLISH = "EN"
        MISC = "MC"

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="quizzes")
    points = models.PositiveSmallIntegerField(default=1)
    subject = models.CharField(max_length=2, choices=Subject.choices)
    specific_subject = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    taken = models.ManyToManyField(User, through="QuizData")

    @property
    def valid_questions(self):
        valid_questions: int = 0

        for question in self.question_set.all():
            if(question.answerable):
                valid_questions += 1

        return valid_questions

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=200)

    @property
    def answerable(self):
        for choice in self.choice_set.all():
            if(choice.correct):
                return True

        return False

class Choice(models.Model):
    choice = models.CharField(max_length=500)
    correct = models.BooleanField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

class QuizData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

class Score(models.Model):
    score = models.PositiveSmallIntegerField()
    time = models.DateTimeField(auto_now_add=True)
    takenQuiz = models.ForeignKey(QuizData, on_delete=models.CASCADE)

Quizzicle/quizzes/forms.py
from django import forms
from django.db import models

from quizzes.models import Quiz, Question, Choice

class NewQuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'points', 'subject', 'specific_subject']

    def __init__(self, *args, **kwargs):
        super(NewQuizForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'
            visible.field.widget.attrs['id'] = visible.name

class NewQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question']
    
    def __init__(self, *args, **kwargs):
        super(NewQuestionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'
            visible.field.widget.attrs['id'] = visible.name

class NewChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice', 'correct']

    def __init__(self, *args, **kwargs):
        super(NewChoiceForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'
            visible.field.widget.attrs['id'] = visible.name

class SearchForm(forms.Form):
    class SubjectChoices(models.TextChoices):
        NONE = "NA"
        MATH = "MA"
        SCIENCE = "SC"
        HISTORY = "HI"
        ENGLISH = "EN"
        MISC = "MC"

    name = forms.CharField(max_length=50, required=False)
    subject = forms.ChoiceField(choices=SubjectChoices.choices, required=False)
    specific_subject = forms.CharField(max_length=50, required=False)
    author = forms.CharField(max_length=100, required=False)

    def make_mini_form(self):
        self.fields["name"].widget.attrs['placeholder'] = "Search by name..."
        self.fields["name"].widget.attrs['class'] = "mini-search"

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input'
            visible.field.widget.attrs['id'] = visible.name

Quizzicle/quizzes/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpRequest, HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.urls import reverse

from accounts.utils import group_required

from quizzes.forms import NewQuizForm, NewQuestionForm, NewChoiceForm, SearchForm
from quizzes.utils import *
# Create your views here.

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def view_created_quizzes(request: HttpRequest):
    quizzes = Quiz.objects.filter(author=request.user)
    search_form = SearchForm()
    search_form.make_mini_form()

    return render(request, "quizzes/quiz_list.html", {"quizzes": quizzes, "search_form": search_form})

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def create_quiz(request: HttpRequest):
    form = NewQuizForm()
    search_form = SearchForm()
    search_form.make_mini_form()

    context = {"form": form, "search_form": search_form}

    if(request.method == "POST"):
        form = NewQuizForm(request.POST)
        if(form.is_valid()):
            quiz = form.save(commit=False)
            quiz.author = request.user
            quiz.save()

            return redirect(reverse("create_question", args=[quiz.id]))

    return render(request, "quizzes/create_quiz.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def modify_quiz(request: HttpRequest, id: int):
    quiz: Quiz = get_quiz(id)

    if(quiz == None):
        return redirect("view_quizzes")
    elif(quiz.author != request.user):
        return redirect("view_quizzes") # TODO Replace this with a error template
    

    form = NewQuizForm(instance=quiz)
    search_form = SearchForm()
    search_form.make_mini_form()
    questions = quiz.question_set.all()
    context = {"form": form, "quiz": quiz, "questions": questions, "search_form": search_form}

    if(request.method == "POST"):
        form = NewQuizForm(request.POST, instance=quiz)
        if(form.is_valid()):
            form.save()

            return redirect("view_quizzes")

    return render(request, "quizzes/modify_quiz.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def delete_quiz(request: HttpRequest, id: int):
    quiz: Quiz = get_quiz(id)

    if(quiz.author != request.user):
        return redirect("view_quizzes") # TODO Replace this with a error template
    elif(quiz == None):
        return redirect("view_quizzes")

    search_form = SearchForm()
    search_form.make_mini_form()
    context = {"quiz": quiz, "search_form": search_form}

    if(request.method == "POST"):
        quiz.delete()
        return redirect("view_quizzes")

    return render(request, "quizzes/delete_quiz.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def delete_question(request: HttpRequest, id: int):
    question: Question = get_question(id)
    
    if(question == None):
        return redirect("view_quizzes") # TODO Replace this with a error template get_object_or_404?
    
    quiz: Quiz = question.quiz

    if(quiz.author != request.user):
        return redirect("view_quizzes") # TODO Replace this with a error template
    elif(quiz == None):
        return redirect("view_quizzes")

    search_form = SearchForm()
    search_form.make_mini_form()
    context = {"quiz": quiz, "question": question, "search_form": search_form}

    if(request.method == "POST"):
        question.delete()
        return redirect(reverse("modify_quiz", args=[question.quiz.id]))

    return render(request, "quizzes/delete_question.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def create_question(request: HttpRequest, id: int):
    form = NewQuestionForm()
    quiz = get_quiz(id)

    if(quiz == None):
        return redirect("view_quizzes") #TODO Replace with error template
    elif(quiz.author != request.user):
        return redirect("view_quizzes") #TODO replace with error template

    if(request.method == "POST"):
        form = NewQuestionForm(request.POST)
        if(form.is_valid()):
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()

            return redirect(reverse("modify_question", args=[question.id]))

    search_form = SearchForm()
    search_form.make_mini_form()
    context = {"form": form, "quiz": quiz, "search_form": search_form}
    return render(request, "quizzes/create_question.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def modify_question(request: HttpRequest, id: int):
    question: Question = get_question(id)

    if(question == None):
        return redirect("view_quizzes") #TODO replace this with an error template
    elif(question.quiz.author != request.user):
        return redirect("view_quizzes") # TODO Replace this with a error template

    form = NewQuestionForm(instance=question)
    search_form = SearchForm()
    search_form.make_mini_form()
    quiz = question.quiz
    choices = question.choice_set.all()

    choice_forms =[]
    for choice in choices:
        choice_forms.append(NewChoiceForm(instance=choice))

    choices_and_forms = zip(choices, choice_forms)

    if(request.method == "POST"):
        form = NewQuestionForm(request.POST, instance=question)
        if(form.is_valid()):
            form.save()

    context = {"form": form, "choices": choices_and_forms, "question": question, "quiz": quiz, "search_form": search_form}

    return render(request, "quizzes/modify_question.html", context)

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def modify_choice(request: HttpRequest, id: int):
    choice:Choice = get_object_or_404(Choice, id=id)
    question:Question = choice.question
    quiz:Quiz = question.quiz

    if(request.user != quiz.author):
        return redirect("view_quizzes") #TODO replace with error template

    if(request.method == "POST"):
        if(request.POST.get("delete", False)):
            choice.delete()
        elif(request.POST.get("update", False)):
            form = NewChoiceForm(request.POST, instance=choice)
            if(form.is_valid()):
                form.save()

    return redirect(reverse("modify_question", args=[question.id]))

@login_required(login_url="login")
@group_required(group_name="Verified", redirect_url="verify")
def create_choice(request: HttpRequest, id: int):
    form = NewChoiceForm()
    question = get_object_or_404(Question, id=id)
    quiz = question.quiz

    if(quiz == None):
        return redirect("view_quizzes") #TODO Replace with error template
    elif(quiz.author != request.user):
        return redirect("view_quizzes") #TODO replace with error template

    if(request.method == "POST"):
        form = NewChoiceForm(request.POST)
        if(form.is_valid()):
            choice = form.save(commit=False)
            choice.question = question
            choice.save()

            return redirect(reverse("modify_question", args=[question.id]))

    search_form = SearchForm()
    search_form.make_mini_form()
    context = {"form": form, "question": question, "search_form": search_form}
    return render(request, "quizzes/create_choice.html", context)

def get_home(request: HttpRequest):
    search_form = SearchForm()
    search_form.make_mini_form()
    context = {"search_form": search_form}

    return render(request, "quizzes/home.html", context)

def get_search_results(request: HttpRequest):
    form = SearchForm()
    quizzes = Quiz.objects.all()
    search_form = SearchForm()
    search_form.make_mini_form()
    
    if(request.method == "GET"):
        form = SearchForm(request.GET)
        if(form.is_valid()):
            search_parameters = form.cleaned_data
            if(search_parameters.get("name", "")):
                quizzes = quizzes.filter(name__contains=search_parameters["name"])
            if(search_parameters.get("subject", "NA") != "NA" and search_parameters.get("subject", "NA")):
                quizzes = quizzes.filter(subject=search_parameters["subject"])
            if(search_parameters.get("specific_subject", "")):
                quizzes = quizzes.filter(specific_subject__contains=search_parameters["specific_subject"])
            if(search_parameters.get("author", "")):
                quizzes = quizzes.filter(author__username__contains=search_parameters["author"])

    quizzes = [quiz for quiz in quizzes if quiz.valid_questions > 0]
    context = {"form": form, "quizzes": quizzes, "search_form": search_form}
    
    return render(request, "quizzes/search_results.html", context)

def prepare_quiz(request: HttpRequest, id: int):
    search_form = SearchForm()
    search_form.make_mini_form()

    quiz = get_object_or_404(Quiz, id=id)

    if(quiz.valid_questions <= 0):
        return redirect("home")

    context = {"search_form": search_form, "quiz": quiz}
    return render(request, "quizzes/start_quiz.html", context)

def take_quiz(request: HttpRequest, id: int):
    valid_questions = []
    valid_choices = []

    search_form = SearchForm()
    search_form.make_mini_form()

    quiz: Quiz = get_object_or_404(Quiz, id=id)
    if(quiz.valid_questions <= 0):
        return redirect("home")

    for question in quiz.question_set.all():
        if(question.answerable):
            valid_questions.append(question)
            valid_choices.append(question.choice_set.all())

    context = {"search_form": search_form, "quiz": quiz, "questions_and_choices": zip(valid_questions, valid_choices)}
    return render(request, "quizzes/quiz.html", context)

def get_results(request: HttpRequest, id: int):

Quizzicle/quizzes/templates/quizzes/create_choice.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'quizzes/css/create_choice.css' %}">
{% endblock %}

{% block title %}Create Choice | StudyBee{% endblock %}
    
{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Create Question</h1></div>
            <div class="cancel">
                <a href="{% url 'modify_question' question.id %}"><p>Cancel</p></a>
            </div>
        </div>
        
        <div class="content">
            <hr>
            <form action="" method="post">
                {% csrf_token %}
                
                {% for field in form %}
                    <label for="{{field.name}}">{{field.label}}</label>
                    {{field}}
                {% endfor %}
                <input class="submit" type="submit" value="Create Choice">
            </form>

            <div class="messages" {% if not messages %}hidden{% endif %}>
                {% if messages %}
                    {% for message in messages %}
                        <p class="message">{{message}}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/create_question.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'quizzes/css/create_question.css' %}">
{% endblock %}

{% block title %}Create Question | StudyBee{% endblock %}
    
{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Create Question</h1></div>
            <div class="cancel">
                <a href="{% url 'modify_quiz' quiz.id %}"><p>Cancel</p></a>
            </div>
        </div>
        
        <div class="content">
            <hr>
            <form action="" method="post">
                {% csrf_token %}
                
                {% for field in form %}
                    <label for="{{field.name}}">{{field.label}}</label>
                    {{field}}
                {% endfor %}
                <input class="submit" type="submit" value="Create Question">
            </form>

            <div class="messages" {% if not messages %}hidden{% endif %}>
                {% if messages %}
                    {% for message in messages %}
                        <p class="message">{{message}}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/create_quiz.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'quizzes/css/create_quiz.css' %}">
{% endblock %}

{% block title %}Create Quiz | StudyBee{% endblock %}

{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Create Quiz</h1></div>
            <div class="cancel">
                <a href="{% url 'view_quizzes' %}"><p>Cancel</p></a>
            </div>
        </div>
        
        <div class="content">
            <hr>
            <form action="" method="post">
                {% csrf_token %}
                
                {% for field in form %}
                    <label for="{{field.name}}">{{field.label}}</label>
                    {{field}}
                {% endfor %}
                <input class="submit" type="submit" value="Create Quiz">
            </form>

            <div class="messages" {% if not messages %}hidden{% endif %}>
                {% if messages %}
                    {% for message in messages %}
                        <p class="message">{{message}}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/delete_question.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/delete_quiz.css' %}">
{% endblock %}

{% block title %}Delete Question | StudyBee{% endblock %}

{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Delete Question</h1></div>
            <div class="cancel">
                <a href="{% url 'modify_quiz' quiz.id %}"><p>Cancel</p></a>
            </div>
        </div>
        
        <div class="content">
            <hr>
            <h2>Are you sure you want to delete: {{question.question}}</h2>
            <form action="" method="post">
                {% csrf_token %}
                <input class="submit" type="submit" value="Delete Question">
            </form>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/delete_quiz.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'quizzes/css/delete_quiz.css' %}">
{% endblock %}

{% block title %}Delete Quiz | StudyBee{% endblock %}

{% block content %}
        <main>
            <div class="tools">
                <div></div>
                <div><h1>Delete Quiz</h1></div>
                <div class="cancel">
                    <a href="{% url 'modify_quiz' quiz.id %}"><p>Cancel</p></a>
                </div>
            </div>
            
            <div class="content">
                <hr>
                <h2>Are you sure you want to delete {{quiz.name}}</h2>
                <form action="" method="post">
                    {% csrf_token %}
                    <input class="submit" type="submit" value="Delete Quiz">
                </form>
            </div>
        </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/header.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Template Page{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'quizzes/css/header.css' %}">
        
        {% block styles %}
        {% endblock %}
    </head>
    <body>
        <nav>
            <div class="left">
                <a href="{% url 'home' %}"><p class="logo">StudyBee</p></a>
                <a href="{% url 'home' %}"><p class="nav-link">Home</p></a>
                <a href=""><p class="nav-link">Subjects</p></a>
                <a href="{% url 'view_quizzes' %}"><p class="nav-link">Create</p></a>
            </div>

            <div class="right">
                <form class="search" action="{% url 'search' %}" method="get">
                    {{search_form.name}}
                </form>
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}"><p class="logout">Log out</p></a>
                {% else %}
                <a href="{% url 'login' %}"><p class="login">Log in</p></a>
                <a href="{% url 'register' %}"><p class="register">Sign up</p></a>
                {% endif %}
            </div>
        </nav>

        {% block content %}{% endblock %}

    </body>
</html>

Quizzicle/quizzes/templates/quizzes/home.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/home.css' %}">
{% endblock %}

{% block title %}Home | StudyBee{% endblock %}

{% block content %}
    <main>
        <div class="content">
            <a class='link' href="{% url 'search' %}"><p>Let's Go</p></a>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/modify_question.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/modify_question.css' %}">
{% endblock %}


{% block title %}Modify Question | StudyBee{% endblock %}

{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Modify Question</h1></div>
            <div class="buttons">
                <a class="cancel" href="{% url 'modify_quiz' quiz.id %}"><p>Go Back</p></a>
                <a class="delete" href="{% url 'delete_question' question.id %}"><p>Delete</p></a>
            </div>
        </div>
        
        <div class="content">
            <div class="form">
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <label for="{{field.name}}">{{field.label}}</label>
                        {{field}}
                    {% endfor %}
                    <input class="submit" type="submit" value="Update Question">
                </form>

                <div class="messages" {% if not messages %}hidden{% endif %}>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="message">{{message}}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div>
                <hr>
                <div class="choice_tools">
                    <div></div>
                    <div><h2>Choices</h2></div>
                    <div class="create">
                        <a href="{% url 'create_choice' question.id %}"><p>Create Choice</p></a>
                    </div>
                </div>
                {% for choice, choice_form in choices %}
                    <form class="choice" method="post" action="{% url 'modify_choice' choice.id %}">
                        {% csrf_token %}
                        <div class="item1">{{choice_form.choice}}</div>
                        <div class="item2"></div>
                        <div class="item3"><input class="delete_choice" type="submit" name="delete" value="Delete"></div>
                        <div class="item4"><label for="correct">Correct Answer</label> {{choice_form.correct}}</div>
                        <div class="item5"></div>
                        <div class="item6"><input class="update" type="submit" name="update" value="Update"></input></div>
                    </form>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/modify_quiz.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'quizzes/css/modify_quiz.css' %}">
{% endblock %}

{% block title %}Modify Quiz | StudyBee{% endblock %}

{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Modify Quiz</h1></div>
            <div class="buttons">
                <a class="cancel" href="{% url 'view_quizzes' %}"><p>Cancel</p></a>
                <a class="delete" href="{% url 'delete_quiz' quiz.id %}"><p>Delete</p></a>
            </div>
        </div>
        
        <div class="content">
            <div class="form">
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <label for="{{field.name}}">{{field.label}}</label>
                        {{field}}
                    {% endfor %}
                    <input class="submit" type="submit" value="Update Quiz">
                </form>

                <div class="messages" {% if not messages %}hidden{% endif %}>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="message">{{message}}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div>
                <hr>
                <div class="question_tools">
                    <div></div>
                    <div><h2>Questions</h2></div>
                    <div class="create">
                        <a href="{% url 'create_question' quiz.id %}"><p>Create Question</p></a>
                    </div>
                </div>
                {% for question in questions %}
                    <div class="question">
                        <div class="item1"><p>{{question.question}}</p></div>
                        <div class="item2"><a href="{% url 'delete_question' question.id %}"><p>Delete</p></a></div>
                        <div class="item3"><p></p></div>
                        <div class="item4"><p>Number of choices: {{question.choice_set.all|length}}</p></div>
                        <div class="item5"><p></p></div>
                        <div class="item6"><a href="{% url 'modify_question' question.id %}"><p>Modify</p></a></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/quiz_list.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/quiz_list.css' %}">
{% endblock %}

{% block title %}All Created Quizzes | StudyBee{% endblock %}
    
{% block content %}
    <main>
        <div class="tools">
            <div></div>
            <div><h1>Quiz List</h1></div>
            <div class="create">
                <a href="{% url 'create_quiz' %}"><p>Create Quiz</p></a>
            </div>
        </div>
        
        <div class="content">
            
            <hr>

            {% for quiz in quizzes %}
                <div class="quiz">
                    <div class="item1"><p>{{quiz.name}}</p></div>
                    <div class="item2"></div>
                    <div class="item3"><p>Points: {{quiz.points}}</p></div>
                    <div class="item4"><p>Subject: {{quiz.get_subject_display}}</p></div>
                    <div class="item5"></div>
                    <div class="item6"><p>{{quiz.specific_subject}}</p></div>
                    <div class="item7"></div>
                    <div class="item8"><p>Questions: {{quiz.question_set.all|length}}</p></div>
                    <div class="item9"></div>
                    <div class="item10"><a href="{% url 'modify_quiz' quiz.id %}"><p>Modify</p></a></div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/search_results.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/search_results.css' %}">
{% endblock %}

{% block title %}Search | StudyBee{% endblock %}

{% block content %}
    <main>
        <div>
            <p>Search</p>
            <form action="" method="get">
                {{form}}

                <input type="submit" value="Search">
            </form>
        </div>

        <div class="tools">
            <div><h1>Quiz List</h1></div>
        </div>
        
        <div class="content">
            
            <hr>

            {% for quiz in quizzes %}
                <div class="quiz">
                    <div class="item1"><p>{{quiz.name}}</p></div>
                    <div class="item2"></div>
                    <div class="item3"><p>Points: {{quiz.points}}</p></div>
                    <div class="item4"><p>Subject: {{quiz.get_subject_display}}</p></div>
                    <div class="item5"></div>
                    <div class="item6"><p>{{quiz.specific_subject}}</p></div>
                    <div class="item7"></div>
                    <div class="item8"><p>Created by: {{quiz.author}} </p></div>
                    <div class="item9"><p>Questions: {{quiz.question_set.all|length}}</p></div>
                    <div class="item10"></div>
                    <div class="item11"><a href="{% url 'prepare_quiz' quiz.id %}"><p>Take Quiz</p></a></div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

Quizzicle/quizzes/templates/quizzes/start_quiz.html
{% extends "quizzes/header.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'quizzes/css/start_quiz.css' %}">
{% endblock %}

{% block title %}{{quiz.name}} Quiz{% endblock %}

{% block content %}
    <main>
        <div class="content">
            <p>{{quiz.name}}</p>
            <a href="{% url 'take_quiz' quiz.id %}"><p>Start</p></a>
            <a href="{% url 'search' %}"><p>Go back</p></a>

            <p>Questions: {{quiz.valid_questions}}</p>
        </div>
    </main>
{% endblock %}